//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalsWPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnimalsDBEntities : DbContext
    {
        public AnimalsDBEntities()
            : base("name=AnimalsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<CatBreed> CatBreeds { get; set; }
        public virtual DbSet<Cat> Cats { get; set; }
        public virtual DbSet<DogBreed> DogBreeds { get; set; }
        public virtual DbSet<Dog> Dogs { get; set; }
        public virtual DbSet<Domecile> Domeciles { get; set; }
    }
}
