//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalsWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat
    {
        public int CatID { get; set; }
        public Nullable<bool> LikesCatnip { get; set; }
        public Nullable<int> CatBreed { get; set; }
        public Nullable<int> DomecileID { get; set; }
        public Nullable<int> AnimalID { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual CatBreed CatBreed1 { get; set; }
        public virtual Domecile Domecile { get; set; }
    }
}
