//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalsWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dog
    {
        public int DogID { get; set; }
        public Nullable<bool> PlaysFetch { get; set; }
        public Nullable<int> DogBreedID { get; set; }
        public Nullable<int> DomecileID { get; set; }
        public Nullable<int> AnimalID { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual DogBreed DogBreed { get; set; }
        public virtual Domecile Domecile { get; set; }
    }
}
